# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "firewire_ohci" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a049e035-2542-472e-ad90-4e0353d26185";
      fsType = "ext4";
    };

  fileSystems."/var/lib/plex/backup" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/var/lib/plex/media-channels" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/var/lib/plex/media-movies" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/var/lib/plex/media-music" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/var/lib/plex/media-photos" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/var/lib/plex/media-shows" =
    { device = "systemd-1";
      fsType = "autofs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/67E3-17ED";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/var/lib/containers/storage/overlay" =
    { device = "/var/lib/containers/storage/overlay";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
